### ISSUE TITLE
Player does not collide with other props

### ISSUE THREAD

**Issue by Kyrasuum** [oochitecht/planetview#11]
Fixing the collision box seems to have induced this error.
It is unknown the extents of what the player can or cannot collide with under this bug.

**Comment by zguh** [comment]
oh my how did this happen

**Comment by Kyrasuum** [comment]
Okay, Im able to get collision callbacks using the following snippet:

```
ply:PhysicsInit(SOLID_CUSTOM)
ply:EnableCustomCollisions( true )
ply:SetSolid( SOLID_VPHYSICS )
ply:SetCollisionGroup(COLLISION_GROUP_INTERACTIVE)
ply:GetPhysicsObject():Wake()
ply:GetPhysicsObject():EnableMotion( true )
ply:GetPhysicsObject():EnableCollisions( true )
ply:AddCallback("PhysicsCollide",plyCollis)

ply:SetSolidFlags(19)
ply:SetMoveType( MOVETYPE_VPHYSICS )
```

.
.
.

```
function plyCollis( ply, data )
    print("COLLIDING")
end
```

with plyCollis being our physcallback function handling the collision.
Unfortunately this comes with the problem that we need to figure out how to handle collisions and this issue becomes dependent on our movement rewrite because it disables the old move type.

**Comment by Kyrasuum** [comment]
Just to update, the previous solution does not provide physics callbacks on anything but world.  The previous solution has therefore been tabled while we explore alternatives.

Ideas thus far:
Utilize pcam as OOBB for the player's collisions.  This comes with the downside of approximating collisions.
Implement a ragdoll as the player's collision object.  This seems like the best solution but the implementation is not yet understood.
Ultimate fail safe: Make the player's hull a small square centered around their feet so they can always collide with something at the bottom of their model.  Cons: Majority of their model would not collide, Looks weird.

**Comment by Kyrasuum** [comment]
Okay, i have done a few additional tests now.  The results are as follows:

The bones of the player seem to behave correctly, in that they follow the player model as they should be.
The hitboxes 'should' therefore be following the bones similarly.

This might indicate that the hitboxes and the collision box are two separate entities. IE: you can collide with an object without a bone colliding with the object or vice versa.

The following is the testing code which discovered this:

```
    render.SetColorMaterial()
    for i=0,ply:GetBoneCount() - 1,1 do
        local pos, ang = ply:GetBonePosition( i )
        if ( ply:BoneHasFlag(i,BONE_USED_BY_HITBOX) ) then
            render.DrawSphere( pos, 1, 50, 50, Color( 255, 0, 0, 255 ) )
        end
    end
```

**Comment by Kyrasuum** [comment]
Okay, upon further testing I discovered that this was caused from prop side not player side.  Overriding prop spawn functions without calling the base class didnt allow them to have physics.  This issue has since been resolved.

This can be considered closed pending any further bugs to physics.
